apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fve
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  rules:
    - host: fve.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fve-api
                port: { number: 80 }
